### ISSUE TITLE
라우팅 적용하기

### ISSUE THREAD

**Issue by KwonTF** [ssu-esc/fe#3]
페이 라우와 같은 그의 폭.풍 라우팅이 시작된다

- `/` 기본 url: 전체 곡 리스트
- `/artist`: 작곡자 정렬 리스트
- `/album`: 앨범 정렬 리스트
- `/playlist`: 플레이 리스트
- `/login`: 로그인 페이지

**Comment by niceb5y** [comment]
근데 매번 이슈까지 만들 필요는 있나?
