### ISSUE TITLE
개선 사항 제안

### ISSUE THREAD

**Issue by niceb5y** [ssu-esc/fe#8]
- [x] `common`과 `component` 디렉토리 합치기

  * 둘은 역할에 딱히 차이 없는 듯
- [x] `LoginController`와 `LoginComponent`합치기
  * 재사용적인 측면에서 굳이 두 컴포넌트를 분리시킬 필요는 없어보임
  * 겸사겸사 `Controller` 디렉토리도 지워버리고
  * `LoginComponent` 이름도 그냥 `Login`으로 하는 게 좋다고 생각
- [ ] 불필요한 `index.css`, `app.css` 지우기
  * CSS의 사용 방법을 하나로 통일할 필요가 있다고 생각함
- [ ] 일관성 있는 줄바꿈 사용
  * 변수 선언이 붙었다가 떨어졌다가 하는 그거
- [x] `material-ui`의 네이티브 컴포넌트 사용하기
  * 통일성, 개발 속도, 확장성 측면에서...
  * 예를 들면 `Content` 대신 `material-ui`의 `Container`를 사용한다던가 하는.
  * 버튼도 굳이 스타일을 직접 깎을 필요가 있...나?
- [ ] 테스트 코드 작성하기
  * 해주세요

**Comment by KwonTF** [comment]
테스트코드 짜는법 모름

**Comment by niceb5y** [comment]
킁

나의 iPhone에서 보냄

**Comment by niceb5y** [comment]
#9 에서 일단 해결된 걸로.
